services:
  mysql:
    image: 'mysql:latest'
    container_name: 'elm-springcloud-mysql'
    environment:
      - 'MYSQL_DATABASE=elm_springcloud'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=12345678'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    container_name: 'elm-springcloud-redis'
    environment:
      - 'REDIS_PASSWORD=12345678'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'elm-springcloud-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=root'
      - 'RABBITMQ_DEFAULT_PASS=12345678'
    ports:
      - '5672:5672'
      - '15672:15672'
  nacos:
    image: 'nacos/nacos-server:v2.4.3'
    container_name: 'elm-springcloud-nacos'
    environment:
      - 'MODE=standalone'
    ports:
      - '8848:8848'
      - '9848:9848'
