spring:
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345678
      database: 0
  datasource:
    url: jdbc:mysql://localhost:33061/elm_springcloud
    username: root
    password: 12345678
#    url: jdbc:mysql://localhost:33070/elm_db
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: localhost
    username: root
    password: 12345678
    virtual-host: /
  mail:
    host: smtp.163.com
    username: linxy20040304@163.com
    password: PXILBFPDDKSNRFAI

server:
  port: 17000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
