spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
  main:
    web-application-type: reactive
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 200
  data:
    redis:
      sentinel:
        password: 12345678
        master: mymaster
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000ms
      password: 12345678

server:
  port: 80