spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /api/account/**
        - id: test-route
          uri: lb://test-service
          predicates:
            - Path=/api/test/**
        - id: test2-route
          uri: lb://test2-service
          predicates:
            - Path=/api/test2/**