spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345678
      database: 0
  main:
    web-application-type: reactive
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 200
  datasource:
    url: jdbc:mysql://localhost:3306/elm_springcloud
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80