spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:7777,127.0.0.1:8888,127.0.0.1:9999
  main:
    web-application-type: reactive
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 200

server:
  port: 80