spring:
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/api/account/**
        - id: business-route
          uri: lb://business-service
          predicates:
            - Path=/api/business/**
        - id: food-route
          uri: lb://food-service
          predicates:
            - Path=/api/food/**
        - id: address-route
          uri: lb://address-service
          predicates:
              - Path=/api/deliveryAddress/**
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
        - id: orders-route
          uri: lb://orders-service
          predicates:
              - Path=/api/orders/**
        - id: test-route
          uri: lb://test-service
          predicates:
            - Path=/api/test/**
        - id: test2-route
          uri: lb://test2-service
          predicates:
            - Path=/api/test2/**